### ISSUE TITLE
Any underwater simulation in Issac Gym?

### ISSUE THREAD

**Issue by BiligeYang** [wangcongrobot/awesome-isaac-gym#3]
Hi, I saw you have been doing underwater robotics and simulations. I am a PhD student at Yale, researching a similar topic. Have you been able to find a good simulator for underwater robotics? Thanks!

**Comment by robotlearning123** [comment]
Hi, I’ve tried several simulators for underwater robots, and the choice really depends on the specific task. UUV_Simulator/DAVE is one of the more popular underwater simulators, but it’s based on Gazebo/ROS. For simpler swimming tasks, I think MuJoCo could be a good option. As for Isaac Gym, you'll need to handle buoyancy and drag calculations yourself, possibly by adding a plugin. Feel free to email me if you'd like more details!

**Comment by BiligeYang** [comment]
Thank you so much. This is very helpful. Do you know if the GPU parallelized version of Mujoco (MJX) can still handle the fluid environment?

**Comment by robotlearning123** [comment]
Not fully supported. But the simple fluid is fine.

**Comment by robotlearning123** [comment]
Two update for underwater simulation:
https://github.com/wangcongrobot/awesome-isaac-gym/commit/9dd4ab654a5cb826882add548d8ff053f6e48b8b
https://github.com/wangcongrobot/awesome-isaac-gym/commit/bba1bb15d593820e6d700b106ab3479486e8faf3
